export const SET_USERTOKEN = 'SET_USERTOKEN';
export const SET_USERINFO = 'SET_USERINFO';
export const SET_POSTS = 'SET_POSTS';
export const SET_SEARCHEDPOSTS = 'SET_SEARCHEDPOSTS';
export const SET_POSTINFO = 'SET_POSTINFO';
